server:
  port: 8849
  servlet:
    context-path: /purple
spring:
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-wait: -1ms
        max-idle: 8
        min-idle: 1
    timeout: PT10S


